// Generated by scripts/generate-exports.js
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

// 1. 获取当前文件所在的目录 (native/descriptionInfo)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 2. 创建 require 用于加载 .node
const require = createRequire(import.meta.url);

// 3. 定位 .node 文件
let binaryPath = '';
// 开发环境路径
const devPath = path.join(process.cwd(), 'native', 'descriptionInfo', 'build', 'Release', 'descriptionInfo.node');
// 生产环境路径
const prodPath = path.join(__dirname, '../../native/descriptionInfo/build/Release', 'descriptionInfo.node');

if (fs.existsSync(devPath)) {
    binaryPath = devPath;
} else {
    binaryPath = prodPath;
    
    if (!fs.existsSync(binaryPath)) {
        // 尝试从 Electron 资源目录查找
        if (process.resourcesPath) {
             binaryPath = path.join(process.resourcesPath, 'app.asar.unpacked', 'native', 'descriptionInfo', 'build', 'Release', 'descriptionInfo.node');
        }
    }
}

if (!fs.existsSync(binaryPath)) {
    console.error('[Native Module Error] Could not find ' + 'descriptionInfo.node');
    console.error('Searched Dev Path: ' + devPath);
    console.error('Searched Prod Path: ' + prodPath);
    throw new Error('Native module not found: ' + 'descriptionInfo.node');
}

// 4. 加载模块
const nativeModule = require(binaryPath);

// 5. 导出
export default nativeModule;

// 如果你需要解构导入 (import { xxx } from ...)，请依赖 index.d.ts 的提示
// 或者在这里手动添加导出，例如：
export const getFileDescription = nativeModule.getFileDescription;
