const fs = require('fs');
const path = require('path');

// 1. 配置路径
const rootDir = path.resolve(__dirname, '..');
const nativeDir = path.join(rootDir, 'native');

const targetModules = process.argv.slice(2).filter(arg => !arg.startsWith('-'));

console.log('\x1b[36mGenerating ESM/CJS compatible wrappers...\x1b[0m\n');

if (!fs.existsSync(nativeDir)) {
    console.error('Native directory not found.');
    process.exit(1);
}

let modules = fs.readdirSync(nativeDir).filter(dir => {
    return fs.statSync(path.join(nativeDir, dir)).isDirectory() &&
        fs.existsSync(path.join(nativeDir, dir, 'binding.gyp'));
});

// 如果用户指定了目标模块，进行筛选
if (targetModules.length > 0) {
    console.log(`\x1b[33m[Filter] User requested to build only: ${targetModules.join(', ')}\x1b[0m`);

    modules = modules.filter(modName => {
        // 支持精确匹配或包含匹配
        const isMatch = targetModules.some(target =>
            modName === target || modName.toLowerCase().includes(target.toLowerCase())
        );
        return isMatch;
    });

    if (modules.length === 0) {
        console.error(`\x1b[31m[Error] No matching modules found for inputs: ${targetModules.join(', ')}\x1b[0m`);
        console.error(`Available modules: ${fs.readdirSync(nativeDir).join(', ')}`);
        process.exit(1);
    }
}

modules.forEach(modName => {
    const modPath = path.join(nativeDir, modName);
    const gypPath = path.join(modPath, 'binding.gyp');

    // 获取 target_name
    let targetName = modName;
    try {
        const gypContent = fs.readFileSync(gypPath, 'utf8');
        const match = gypContent.match(/['"]target_name['"]\s*:\s*['"](.+?)['"]/);
        if (match && match[1]) targetName = match[1];
    } catch (e) { }

    console.log(`Processing [${modName}]`);

    // 生成 index.js

    const safeIndexJsContent = `// Generated by scripts/generate-exports.js
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

// 1. 获取当前文件所在的目录 (native/${modName})
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 2. 创建 require 用于加载 .node
const require = createRequire(import.meta.url);

// 3. 定位 .node 文件
let binaryPath = '';
// 开发环境路径
const devPath = path.join(process.cwd(), 'native', '${modName}', 'build', 'Release', '${targetName}.node');
// 生产环境路径
const prodPath = path.join(__dirname, '../../native/${modName}/build/Release', '${targetName}.node');

if (fs.existsSync(devPath)) {
    binaryPath = devPath;
} else {
    binaryPath = prodPath;
    
    if (!fs.existsSync(binaryPath)) {
        // 尝试从 Electron 资源目录查找
        if (process.resourcesPath) {
             binaryPath = path.join(process.resourcesPath, 'app.asar.unpacked', 'native', '${modName}', 'build', 'Release', '${targetName}.node');
        }
    }
}

if (!fs.existsSync(binaryPath)) {
    console.error('[Native Module Error] Could not find ' + '${targetName}.node');
    console.error('Searched Dev Path: ' + devPath);
    console.error('Searched Prod Path: ' + prodPath);
    throw new Error('Native module not found: ' + '${targetName}.node');
}

// 4. 加载模块
const nativeModule = require(binaryPath);

// 5. 导出
export default nativeModule;

// 如果你需要解构导入 (import { xxx } from ...)，请依赖 index.d.ts 的提示
// 或者在这里手动添加导出，例如：
// export const getProcesses = nativeModule.getProcesses;
`;

    if (fs.existsSync(path.join(modPath, 'index.js'))) {
        fs.unlinkSync(path.join(modPath, 'index.js'));
    }

    fs.writeFileSync(path.join(modPath, 'index.js'), safeIndexJsContent);

    // 生成 index.d.ts (保持不变)
    const dtsPath = path.join(modPath, 'index.d.ts');
    if (!fs.existsSync(dtsPath) || fs.readFileSync(dtsPath, 'utf8').includes('AUTO-GENERATED-TYPES')) {
        const dtsContent = `// AUTO-GENERATED-TYPES
// Remove this comment to prevent overwrite
declare const nativeModule: any;
export default nativeModule;
// export function getProcesses(): any;
`;
        fs.writeFileSync(dtsPath, dtsContent);
    }
});

console.log('\n\x1b[32mDone!\x1b[0m');